### ISSUE TITLE
Request: armor and armor toughness not working

### ISSUE THREAD

**Issue by BonNubbers** [Darkhax-Minecraft/AttributeFix#16]
so there were two attributes that didnt really work at all, the armor and armor toughness. so i wore a full set of allthemodium armor, then i tried to test to see if the all the attributes work, so i summoned a strong mob like an iron golem, i turns out i took half a heart/a full heart of damage every time, and i thought, "hol up, somethings wrong", then i took off all my armor, then used commands to set my armor points to 30 for comparision. It turns out i take the exact same damage as i did before. is there anything i or you can do?

**Comment by DavidGodinho** [comment]
Are you using the Origins mod or any mod that gives you base armor? I just discovered there seems to be a conflict with it when using the shulk race from Origins mod for some reason.

**Comment by BonNubbers** [comment]
i dont think so.

**Comment by Darkhax** [comment]
Hello, sorry for the late reply. 

This mod does not change any of the calculations or formulas used by vanilla, it only changes the maximum values that can be put into those formulas. The vanilla armor formula produces effectively the same result after 30 armor points. There are mods made by other developers that will change the formula for you however I did not feel it was appropriate to put a feature like that in this mod. 

You can confirm this mod is working by spawning a mob with over 10,000 health and a sword that does 1,000 damage. Players expect that it would take ten hits to kill the mob but it actually takes two in vanilla. This is because Vanilla caps health to 1024. With this mod installed it should take ten hits as expected.
